name: Default

env:
  ACTION_ENVIRONMENT: CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.21

      - name: Build
        run: go build -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@master
        with:
          version: latest
          skip-cache: true
          skip-save-cache: true
          args: --timeout=3m --issues-exit-code=0 ./...

      - name: Test
        run: go test -race -v -coverprofile=coverage_temp.out  -covermode=atomic ./...

      - name: Remove mocks and examples from coverage
        run: grep -v -e "/eebus-go/mocks/" -e "/eebus-go/usecases/mocks/" -e "/eebus-go/examples/" coverage_temp.out > coverage.out

      - name: Send coverage
        uses: coverallsapp/github-action@v2
        with:
          file: coverage.out

      - name: Run Gosec Security Scanner
        uses: securego/gosec@v2.20.0
        with:
          # we let the report trigger content trigger a failure using the GitHub Security features.
          args: '-no-fail -fmt sarif -out results.sarif ./...'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif